site_name: Gambit Scheme

repo_url: https://github.com/gambit/gambit
repo_name: gambit/gambit
edit_uri: edit/master/docs/

nav:
  - Home:
      - index.md
  - Manual:
      - manual/index.md
      - The Gambit system:
          - manual/the_gambit_system/index.md
          - manual/the_gambit_system/accessing_the_system_files.md
      - The Gambit Scheme interpreter:
          - manual/gsi/index.md
          - manual/gsi/interactive_mode.md
          - manual/gsi/batch_mode.md
          - manual/gsi/module_management_mode.md
          - manual/gsi/customization.md
          - manual/gsi/process_exit_status.md
          - manual/gsi/scheme_scripts.md
      - The Gambit Scheme compiler:
          - manual/gsc/index.md
          - manual/gsc/interactive_mode.md
          - manual/gsc/customization.md
          - manual/gsc/batch_mode.md
          - manual/gsc/link_files.md
          - manual/gsc/procedures.md
      - Runtime options:
          - manual/runtime_options/index.md
      - Debugging:
          - manual/debugging/index.md
          - manual/debugging/debugging_model.md
          - manual/debugging/debugging_commands.md
          - manual/debugging/debugging_example.md
          - manual/debugging/procedures.md
          - manual/debugging/console_line_editing.md
          - manual/debugging/emacs_interface.md
      - Scheme extensions:
          - manual/scheme_extensions/index.md
          - manual/scheme_extensions/extensions_to_standard_procedures.md
          - manual/scheme_extensions/extensions_to_standard_special_forms.md
          - manual/scheme_extensions/miscellaneous_extensions.md
          - manual/scheme_extensions/undocumented_extensions.md
      - Modules:
          - manual/modules/index.md
          - manual/modules/legacy_modules.md
          - manual/modules/primitive_modules.md
          - manual/modules/primitive_procedures.md
          - manual/modules/r7rs_compatible_modules.md
          - manual/modules/installing_modules.md
          - manual/modules/compiling_modules.md
      - Built-in data types:
          - manual/built_in_data_types/index.md
          - manual/built_in_data_types/numbers.md
          - manual/built_in_data_types/booleans.md
          - manual/built_in_data_types/pairs_and_lists.md
          - manual/built_in_data_types/symbols_and_keywords.md
          - manual/built_in_data_types/characters_and_strings.md
          - manual/built_in_data_types/vectors.md
          - manual/built_in_data_types/homogeneous_numeric_vectors.md
          - manual/built_in_data_types/hashing_and_weak_references.md
      - Records:
          - manual/records/index.md
      - Threads:
          - manual/threads/index.md
          - manual/threads/introduction.md
          - manual/threads/thread_objects.md
          - manual/threads/mutex_objects.md
          - manual/threads/condvar_objects.md
          - manual/threads/fairness.md
          - manual/threads/memory_coherency.md
          - manual/threads/timeouts.md
          - manual/threads/primordial_thread.md
          - manual/threads/procedures.md
      - Dynamic environment:
          - manual/dynamic_environment/index.md
      - Exceptions:
          - manual/exceptions/index.md
      - Host environment:
          - manual/host_environment/index.md
      - I/O and ports:
          - manual/io_and_ports/index.md
      - Lexical syntax and readtables:
          - manual/lexical_syntax_and_readtables/index.md
      - C-interface:
          - manual/c_interface/index.md
      - System limitations:
          - manual/system_limitations/index.md
      - Copyright and license:
          - manual/copyright_and_license/index.md
  - How-tos:
      - howtos/index.md

theme:
  name: material
  logo: assets/gambit.png
  favicon: assets/favicon.ico
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.tabs
    - navigation.indexes
    # - navigation.sections
    # - navigation.expand
    - toc.follow
    - content.code.annotate
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html

plugins:
  - search
  - social
  - git-revision-date-localized:
      enable_creation_date: true
