site_name: Gambit Scheme

repo_url: https://github.com/gambit/gambit
repo_name: gambit/gambit
edit_uri: edit/master/docs/


theme:
  name: material
  logo: assets/gambit.png
  favicon: assets/favicon.ico
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.tabs
    - navigation.indexes
    - navigation.sections
    - navigation.expand
    - toc.follow
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

plugins:
  - search
  - social
  - git-revision-date-localized:
      enable_creation_date: true
